version: '2.3'
services: 

    database:
        image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
        container_name: database
        restart: always
        ports: 
            - 127.0.0.1:1433:1433
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "saPassword01."
        volumes: 
            - ~/envios-canarios/db-data:/var/opt/mssql
        networks: 
            envioscanariosnet:
        
networks:
    envioscanariosnet:
        driver: bridge
        ipam: 
            config: 
                - subnet: 192.168.1.0/24
