version: '2.3'
services: 

    api:
        build:
            context: ./
            dockerfile: ./WebApp-Api-Dokerfile
        container_name: api
        restart: always
        environment: 
            - "ASPNETCORE_ENVIRONMENT=Development"
        ports: 
            - 127.0.0.1:5000:80
        dns: 
            - "8.8.8.8"
        volumes: 
            - ~/envios-canarios/webappapi-logs:/tmp/webappapi-logs
        networks: 
            envioscanariosnet:
                ipv4_address: 192.168.2.2
    
    database:
        build:
            context: ./
            dockerfile: ./SqlServer2019-Database-Dockerfile
        container_name: database
        restart: always
        ports: 
            - 127.0.0.1:1433:1433
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "saPassword01."
        volumes: 
            - ~/envios-canarios/db-data:/var/opt/sqlserver
        networks: 
            envioscanariosnet:
                ipv4_address: 192.168.2.3
        
networks:
    envioscanariosnet:
        driver: bridge
        ipam: 
            config: 
                - subnet: 192.168.2.0/24
