version: '2.3'
services: 

    webapp-api:
        build:
            context: ./
            dockerfile: ./WebApp-Api-DockerFile
        container_name: webapp-api
        restart: always
        environment: 
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "PurchaseApplicationDbConnectionString=Host=192.168.2.3;Database=CanaryDeliveries;Username=postgres;Password=Password01!;"
        ports: 
            - 127.0.0.1:5000:5000
        dns: 
            - "8.8.8.8"
        volumes: 
            - ~/envios-canarios/web-app-api-logs:/tmp/web-app-api-logs
        networks: 
            envioscanariosnet:
                ipv4_address: 192.168.2.2

    backoffice-api:
        build:
            context: ./
            dockerfile: ./Backoffice-Api-DockerFile
        container_name: backoffice-api
        restart: always
        environment: 
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "PurchaseApplicationDbConnectionString=Host=192.168.2.3;Database=CanaryDeliveries;Username=postgres;Password=Password01!;"
            - "JsonWebTokenSecretKey=jwt-devel-secret-key"
        ports: 
            - 127.0.0.1:5001:5000
        dns: 
            - "8.8.8.8"
        volumes: 
            - ~/envios-canarios/backoffice-api-logs:/tmp/backoffice-api-logs
        networks: 
            envioscanariosnet:
                ipv4_address: 192.168.2.5
    
    database:
        image: postgres:13.1
        container_name: database
        restart: always
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "Password01!"
        volumes: 
            - ~/envios-canarios/db-data:/var/lib/postgresql/data
        networks: 
            envioscanariosnet:
                ipv4_address: 192.168.2.3

    migration-manager:
        build:
            context: ./
            dockerfile: ./MigrationManager-DockerFile
        container_name: migration-manager
        environment: 
            - "PurchaseApplicationDbConnectionString=Host=192.168.2.3;Database=CanaryDeliveries;Username=postgres;Password=Password01!;"
        networks: 
            envioscanariosnet:
                ipv4_address: 192.168.2.4
        depends_on:
            - database
        
networks:
    envioscanariosnet:
        driver: bridge
        ipam: 
            config: 
                - subnet: 192.168.2.0/24
